services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - coffee_network

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - coffee_network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - coffee_network

  orders:
    build:
      context: ./
      dockerfile: ./orders/Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - mongodb
      - kafka
#    environment:
#      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/test
    networks:
      - coffee_network

  user-api:
    build:
      context: ./
      dockerfile: ./user-api/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka
    networks:
      - coffee_network

networks:
  coffee_network:
    driver: bridge
    name: coffee-network
